// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Req {
    risposta: Risposta;
}

export interface Risposta {
    "@tipo":         Tipo;
    timestamp:       Timestamp;
    pronto_soccorso: ProntoSoccorso;
}

export enum Tipo {
    Ok = "OK",
}

export interface ProntoSoccorso {
    reparto: Reparto;
}

export interface Reparto {
    codice:                  string;
    descrizione:             string;
    ospedale:                string;
    unita_operativa:         null | string;
    descrizione_ambulatorio: null | string;
    direttore:               null | string;
    localita:                string;
    messaggio:               null | string;
    attesa:                  Ambulatorio;
    ambulatorio:             Ambulatorio;
    osservazione:            Ambulatorio;
    "attesa-media":          Ambulatorio;
}

export interface Ambulatorio {
    bianco:  string;
    verde:   string;
    azzurro: string;
    arancio: string;
    giallo:  string;
    rosso:   string;
}

export enum Timestamp {
    The31032022Ore1340 = "31/03/2022 ore 13:40",
}
